### PR TITLE
Load Gravatar over https #4268

### LINKED ISSUE #4268: New variable to load Gravatar over https or set https as standard
When running over https://  one will get a mixed content warning as gravatars are loaded over http.
The easiest fix I have found so war is by setting 

`AVATAR_GRAVATAR_SSL = True`

in settings.

Hence I´d like to suggest introducing AVATAR_GRAVATAR_SSL as new settings var. If devs do not want to further spoil settings.py (It´s already blown up) I would suggest to just mention it at documentation.

### PR DESCRIPTION
**Pull request by t-book**
This will set the used protocol for loading of gravatar to https as standard.
(Otherwise you will get a mixed contant warning when running your geonode over https)
close https://github.com/GeoNode/geonode/issues/4268

### CODE REVIEW

**Comment by frafra** [comment]
Seems OK to me :-)

**Comment by t-book** [comment]
@frafra thanks! do you have write access here? ;))

**Comment by frafra** [comment]
@t-book no, I do not have it...

**Comment by t-book** [comment]
same same. Let´s wait ... not urgent at all ;)

**Comment by afabiani** [comment]
I don't think it is sufficient. You need to update the version also and then, once merged, push on pypi.

**Comment by t-book** [comment]
true thanks, for reminding!

**Comment by t-book** [comment]
Dear @afabiani I´m closing this PR as I cannot push to to pypi and do not want to produce work for anybody for such a tiny thing. I will mention the correcting settings in docs.

**Pull request closed without merging**
